### ISSUE TITLE
Application will not start successfully

### ISSUE THREAD

**Issue by chenry** [Google-IO-Extended-Grand-Rapids/conference_web#53]
_How do you reproduce this issue_
1. `vagrant up`
1. `mvn clean package -PlocalDB && java -jar target/conference-web-0.1.0.jar`
- Which Branch *
- develop
- feature/generate_entities
  When running from feature/generate_entities, instead of conference-web-0.1.0.jar use gs-rest-service-0.1.0.jar

When the application starts, I see the following exceptions:
`... 21 more
Caused by: org.hibernate.AnnotationException: No identifier specified for entity: com.ioextendedgr.web.data.UserXyz
    at org.hibernate.cfg.InheritanceState.determineDefaultAccessType(InheritanceState.java:277)
    at org.hibernate.cfg.InheritanceState.getElementsToProcess(InheritanceState.java:224)
    at org.hibernate.cfg.AnnotationBinder.bindClass(AnnotationBinder.java:732)
    at org.hibernate.cfg.Configuration$MetadataSourceQueue.processAnnotatedClassesQueue(Configuration.java:3762)
    at org.hibernate.cfg.Configuration$MetadataSourceQueue.processMetadata(Configuration.java:3716)
    at org.hibernate.cfg.Configuration.secondPassCompile(Configuration.java:1410)
    at org.hibernate.cfg.Configuration.buildSessionFactory(Configuration.java:1844)
    at org.hibernate.jpa.boot.internal.EntityManagerFactoryBuilderImpl$4.perform(EntityManagerFactoryBuilderImpl.java:850)`

**Comment by jonasrob** [comment]
@chenry I think this will be addressed with the feature/conference_api merge.

**Comment by chenry** [comment]
@jonasrob I just tried, and unfortunately, I am still running into issues...

`mvn clean install -PlocalDB && java -jar target/gs-rest-service-0.1.0.jar`

**Comment by chenry** [comment]
This has been fixed...
